WIN_W :: 1920;
WIN_H :: 1080;

WIN_TITLE :: "Stream OwO";

FONT :: "data/fonts/LythMonoNerdFont-Regular.ttf";
FONT_SIZE :: 60;

BLACK :: Color.{0x00, 0x00, 0x00, 0xFF};
WHITE :: Color.{0xFF, 0xFF, 0xFF, 0xFF};
YELLOW :: Color.{0xFF, 0xFF, 0x00, 0xFF};

// Music
MUSIC_FILE :: "data/music/Siine - Need A Friend.wav";
MUSIC_URL :: "https://music.youtube.com/watch?v=MclRz-NUu9o";
MUSIC_QR :: "qr.png";

// Donation
UPI_TEXT :: "UPI";
UPI_QR_TEXT :: "upi://pay?mode=01&ver=01&pa=swarnaditya.1%40superyes&pn=SWARNADITYA+SINGH&txntype=pay&qrmedium=02";
UPI_QR :: "data/donate.png";
